---
defaultBundleRef: 'community:1.0.0'
imageRepos:
  - id: core
    url: nexus.citeck.ru
  - id: enterprise
    url: enterprise-registry.citeck.ru
    pullSecret: ent-registry
bundleRepos:
  - id: community
    name: Community Bundles
    url: https://github.com/PavelSimonovCiteck/ctklchr.git
    branch: community-kits
    path: kits
  - id: enterprise
    name: Enterprise Bundles
    url: https://github.com/PavelSimonovCiteck/ctklchr.git
    branch: community-kits
    path: kits
applications:
  - id: proxy
    aliases: [ 'EcosProxyApp' ]
  - id: eproc
    aliases: [ 'EcosProcessApp' ]
  - id: emodel
    aliases: [ 'EcosModelApp' ]
  - id: eapps
    aliases: [ 'EcosAppsApp' ]
  - id: gateway
    aliases: [ 'EcosGatewayApp' ]
  - id: uiserv
    aliases: [ 'EcosUiservApp' ]
  - id: history
    aliases: [ 'EcosHistoryApp' ]
  - id: notifications
    aliases: [ 'EcosNotificationsApp' ]
  - id: integrations
    aliases: [ 'EcosIntegrationsApp' ]
  - id: transformations
    aliases: [ 'EcosTransformationsApp' ]
  - id: content
    aliases: [ 'EcosContentApp' ]
  - id: ecom
    aliases: [ 'EcosEcomApp' ]
  - id: service-desk
    aliases: [ 'EcosServiceDeskApp' ]
  - id: edi
    aliases: [ 'EcosEdiApp' ]
  - id: attorneys
    aliases: [ 'EcosPowerAttorneysApp' ]
  - id: ecos-project-tracker
    aliases: [ 'EcosProjectTrackerApp' ]

